version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: stackexchange-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stackexchange
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/scripts
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: stackexchange-app
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./results:/app/results
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: stackexchange
      DATA_DIR: "/app/data"
    command: ["all"]